/**
 * PharmaFlow ERP - Financial Grounding & Number Verification Engine
 * Compares financial figures and assertions generated by the AI against
 * authoritative ledger metrics from AccountingContextAdapter.
 * 
 * CORE RULE: AI IS NOT THE FINANCIAL SOURCE OF TRUTH.
 * Any mismatch between AI-generated numbers and the ledger is flagged as UNVERIFIED_AI_CLAIM.
 */

import { FinancialContextData } from './types';
import { FinancialMath } from '@/core/financial-math';

export type ClaimVerificationStatus = 'VERIFIED' | 'UNVERIFIED_AI_CLAIM' | 'NO_GROUNDING_DATA';

export interface FinancialClaimVerification {
  metric: string;
  metricKey: string;
  metricLabelArabic: string;
  claimedValue: number;
  authoritativeValue: number;
  status: ClaimVerificationStatus;
  discrepancy: number;
  percentageDiff: number;
  isMatch: boolean;
}

export interface GroundingVerificationResult {
  isGrounded: boolean;
  claims: FinancialClaimVerification[];
  flaggedClaims: FinancialClaimVerification[];
  summaryStatus: 'VERIFIED' | 'DISCREPANCY_DETECTED' | 'NO_FINANCIAL_CLAIMS';
  groundedText: string;
  discrepancyCount: number;
}

export class FinancialGroundingService {
  /**
   * Evaluates text generated by AI against authoritative financial context.
   */
  public static verifyFinancialText(
    aiText: string,
    authoritativeContext?: FinancialContextData | Record<string, any>
  ): GroundingVerificationResult {
    if (!aiText || typeof aiText !== 'string') {
      return {
        isGrounded: true,
        claims: [],
        flaggedClaims: [],
        summaryStatus: 'NO_FINANCIAL_CLAIMS',
        groundedText: '',
        discrepancyCount: 0,
      };
    }

    if (!authoritativeContext) {
      return {
        isGrounded: true,
        claims: [],
        flaggedClaims: [],
        summaryStatus: 'NO_FINANCIAL_CLAIMS',
        groundedText: aiText,
        discrepancyCount: 0,
      };
    }

    const claims: FinancialClaimVerification[] = [];
    const authAny = authoritativeContext as Record<string, any>;

    // 1. Check Revenue / Sales claims
    const revenueVal = authoritativeContext.revenue ?? authAny.totalRevenue;
    if (revenueVal !== undefined) {
      this.extractAndVerify(
        aiText,
        /(?:المبيعات|الإيرادات|إجمالي المبيعات|revenue|sales)\s*(?:=|هو|تبلغ|بلغت|:)?\s*([0-9,]+(?:\.[0-9]+)?)/gi,
        revenueVal,
        'revenue',
        'الإيرادات والمبيعات',
        claims
      );
    }

    // 2. Check Net Profit claims
    const profitVal = authoritativeContext.netProfit ?? authAny.netIncome;
    if (profitVal !== undefined) {
      this.extractAndVerify(
        aiText,
        /(?:صافي الربح|الأرباح الصافية|صافي الدخل|إجمالي الأرباح|الأرباح|net profit|net income)\s*(?:=|هو|تبلغ|بلغت|:)?\s*([0-9,]+(?:\.[0-9]+)?)/gi,
        profitVal,
        'netProfit',
        'صافي الربح',
        claims
      );
    }

    // 3. Check Receivables (AR) claims
    const arVal = authoritativeContext.totalAccountsReceivable ?? authAny.totalReceivables;
    if (arVal !== undefined) {
      this.extractAndVerify(
        aiText,
        /(?:الذمم المدينة|مستحقات العملاء|ديون العملاء|accounts receivable|receivables)\s*(?:=|هو|تبلغ|بلغت|:)?\s*([0-9,]+(?:\.[0-9]+)?)/gi,
        arVal,
        'totalAccountsReceivable',
        'الذمم المدينة (مستحقات العملاء)',
        claims
      );
    }

    // 4. Check Payables (AP) claims
    const apVal = authoritativeContext.totalAccountsPayable ?? authAny.totalPayables;
    if (apVal !== undefined) {
      this.extractAndVerify(
        aiText,
        /(?:الذمم الدائنة|مستحقات الموردين|ديون الموردين|accounts payable|payables)\s*(?:=|هو|تبلغ|بلغت|:)?\s*([0-9,]+(?:\.[0-9]+)?)/gi,
        apVal,
        'totalAccountsPayable',
        'الذمم الدائنة (مستحقات الموردين)',
        claims
      );
    }

    // 5. Check COGS claims
    if (authoritativeContext.cogs !== undefined || authAny.cogs !== undefined) {
      this.extractAndVerify(
        aiText,
        /(?:تكلفة المبيعات|تكلفة البضاعة المباعة|cogs|cost of goods sold)\s*(?:=|هو|تبلغ|بلغت|:)?\s*([0-9,]+(?:\.[0-9]+)?)/gi,
        authoritativeContext.cogs ?? authAny.cogs,
        'cogs',
        'تكلفة المبيعات',
        claims
      );
    }

    // 6. Check Cash / Treasury claims
    const cashVal = authAny.totalCash ?? authAny.cash ?? authAny.treasury;
    if (cashVal !== undefined) {
      this.extractAndVerify(
        aiText,
        /(?:النقدية|رصيد الصندوق|النقد في الصندوق|رصيد النقدية|الصندوق|كاش|cash|treasury)\s*(?:في الصندوق|بالخزينة)?\s*(?:=|هو|تبلغ|بلغت|:)?\s*([0-9,]+(?:\.[0-9]+)?)/gi,
        cashVal,
        'totalCash',
        'رصيد النقدية في الصندوق',
        claims
      );
    }

    const discrepancies = claims.filter((c) => c.status === 'UNVERIFIED_AI_CLAIM');
    const isGrounded = discrepancies.length === 0;

    let summaryStatus: GroundingVerificationResult['summaryStatus'] = 'NO_FINANCIAL_CLAIMS';
    if (claims.length > 0) {
      summaryStatus = isGrounded ? 'VERIFIED' : 'DISCREPANCY_DETECTED';
    }

    let groundedText = aiText;
    if (!isGrounded) {
      // Append prominent audit warning with authoritative numbers from the ledger
      const warningLines = discrepancies.map(
        (d) =>
          `• ${d.metricLabelArabic}: الرقم المذكور (${d.claimedValue.toLocaleString()}) غير مطابق لدفتر الأستاذ الرسمي (الرقم المعتمد: ${d.authoritativeValue.toLocaleString()}).`
      );

      groundedText +=
        `\n\n---\n` +
        `**⚠️ تنبيه تدقيق محاسبي للأرقام المالية (UNVERIFIED_AI_CLAIM):**\n` +
        `تم رصد تباين بين الأرقام الاسترشادية ومصدر الحقيقة المالي المعتمد في دفتر الأستاذ:\n` +
        warningLines.join('\n') +
        `\n*القاعدة المحاسبية: محرك الحسابات ودفاتر الأستاذ العام هي المصدر الحصري للحقيقة المالية.*`;
    }

    return {
      isGrounded,
      claims,
      flaggedClaims: discrepancies,
      summaryStatus,
      groundedText,
      discrepancyCount: discrepancies.length,
    };
  }

  private static extractAndVerify(
    text: string,
    regex: RegExp,
    authoritativeVal: number | undefined,
    metricKey: string,
    metricLabelArabic: string,
    claimsList: FinancialClaimVerification[]
  ): void {
    if (authoritativeVal === undefined) return;

    let match: RegExpExecArray | null;
    while ((match = regex.exec(text)) !== null) {
      const rawNumStr = (match[1] ?? match[0]).replace(/,/g, '');
      const claimedNum = parseFloat(rawNumStr);

      if (!Number.isFinite(claimedNum)) continue;

      const authNum = FinancialMath.safeNum(authoritativeVal);
      const discrepancy = FinancialMath.discrepancy(claimedNum, authNum);

      // Allow 1% tolerance or 1.0 currency unit for minor rounding differences
      const allowedTolerance = Math.max(1.0, authNum * 0.01);
      const isMatch = discrepancy <= allowedTolerance;

      const percentageDiff = authNum > 0
        ? FinancialMath.round2((discrepancy / authNum) * 100)
        : (claimedNum > 0 ? 100 : 0);

      claimsList.push({
        metric: metricKey,
        metricKey,
        metricLabelArabic,
        claimedValue: claimedNum,
        authoritativeValue: authNum,
        status: isMatch ? 'VERIFIED' : 'UNVERIFIED_AI_CLAIM',
        discrepancy,
        percentageDiff,
        isMatch,
      });
    }
  }
}
